name 'shep5465'
maintainer 'Sheppy Reno'
maintainer_email 'sheppy.reno@gmail.com'
license 'All rights reserved'
description 'DE1 Assessment'
long_description 'Installs/Configures shep5465'
version '0.1.0'

depends 'apache2'
depends 'rackspace_iptables'
depends 'apt'
